name: spareit_flutter_cli
description: Flutter CLI for SpareIT
maintainer: ECarobaar Technologies Pvt Ltd (Abdul Zelani)
version: 1.0.0
repository: https://github.com/ECarobaar-Technologies-Pvt-Ltd/spareit_flutter_cli
homepage: https://spareit.co.in

environment:
  sdk: ^3.1.2


# Add regular dependencies here.
dependencies:
  # path: ^1.8.0'
  yaml: '>=2.2.0 <4.0.0'
  csv: ^6.0.0
  http: ^0.13.3

executables:
  spareit_flutter_cli: spareit_flutter_cli

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
