name: spareit_flutter_cli
description: Flutter CLI for SpareIT
maintainer: ECarobaar Technologies Pvt Ltd (Abdul Zelani)
version: 1.0.2
repository: https://github.com/ECarobaar-Technologies-Pvt-Ltd/spareit_flutter_cli
homepage: https://spareit.co.in

environment:
  sdk: ">=2.19.0 <4.0.0"


dependencies:
  yaml: '>=2.2.0 <4.0.0'
  csv: '>=5.0.0 <6.0.0'
  http: '>=0.13.3 <2.0.0'

executables:
  spareit_flutter_cli: spareit_flutter_cli

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
